enum ActionTypes {
  TOGGLE_MENU = 'TOGGLE_MENU',
  HIDE_MENU = 'HIDE-MENU',
  TOGGLE_APP_MODE = 'TOGGLE_APP_MODE',
  FETCH_CARDS = 'FETCH_CARDS',
  START_GAME = 'START_GAME',
  STOP_GAME = 'STOP_GAME',
  SET_CURRENT_CARD = 'SET_CURRENT_CARD',
  SET_GAME_CARDS = 'SET_GAME_CARDS',
  ADD_CORRECT = 'ADD_CORRECT',
  ADD_WRONG = 'ADD_WRONG'
}

export default ActionTypes;
