enum ActionTypes {
  TOGGLE_MENU = 'TOGGLE_MENU',
  HIDE_MENU = 'HIDE-MENU',
  TOGGLE_APP_MODE = 'TOGGLE_APP_MODE',
  FETCH_CARDS = 'FETCH_CARDS',
  CARDS_LOADING = 'CARDS_LOADING',
  START_GAME = 'START_GAME',
  STOP_GAME = 'STOP_GAME',
  SET_CURRENT_CARD = 'SET_CURRENT_CARD',
  SET_GAME_CARDS = 'SET_GAME_CARDS',
  ADD_CORRECT = 'ADD_CORRECT',
  ADD_WRONG = 'ADD_WRONG',
  SET_TOKEN = 'SET_TOKEN',
  CLEAR_TOKEN = 'CLEAR_TOKEN',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  UPDATE_WORD = 'UPDATE_WORD',
  CREATE_WORD = 'CREATE_WORD',
  DELETE_WORD = 'DELETE_WORD'
}

export default ActionTypes;
